repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: pdm run black
    args:
      - --safe
      - --quiet
    language: system
    types: [python]
    require_serial: true
    files: ^(hubitatmaker|tests)/.+\.py$
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: pdm run flake8
    language: system
    types: [python]
    require_serial: true
    files: ^(hubitatmaker|tests)/.+\.py$
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: pdm run isort
    language: system
    types: [python]
    require_serial: true
    files: ^(hubitatmaker|tests)/.+\.py$
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: pyright
    language: system
    types: [python]
    require_serial: true
    files: ^(hubitatmaker|tests)/.+\.py$
