#!/usr/bin/env bash

set -e

op=$1
if [[ -z $op ]]; then
	op=help
fi

case $op in
	init)
		pip3 install pipenv
		pipenv install --dev
		pipenv run pre-commit install
		;;
	
	clean)
		rm -rf build dist hubitatmaker.egg-info __pycache__
		;;

	publish)
		latest_tag=$(git describe --tags --abbrev=0)
		package_version=v$(grep __version__ hubitatmaker/__init__.py | awk '{ print substr($3, 2, length($3)-2) }')
		if [[ $latest_tag == $package_version ]]; then
			echo "Update the package version before publishing"
			exit 1
		fi
		rm -rf build dist
		pipenv run python setup.py sdist bdist_wheel

		echo "About to upload version $package_version from dist. If everything looks good, answer 'y': "
		read answer
		if [[ $answer != 'y' ]]; then
			exit 0
		fi

		pipenv run twine upload dist/*
		git tag $package_version
		git push --tags
		;;

	test)
		pipenv run mypy hubitatmaker
		pipenv run python setup.py test
		;;

	help)
		echo "$0 COMMAND"
		echo
		echo "Commands:"
		echo "  init - initialize for development"
		echo "  publish - build and publish to PyPi"
		echo "  test - run type checker and unit tests"
		echo
		;;
	
	version)
		echo $(python -c "import pkg_resources; print(pkg_resources.get_distribution('hubitatmaker').version)")
		;;
esac
